{% set name = "Nuitka" %}
{% set version = "0.5.24.4" %}
{% set sha256 = "9e83383db74983c18372f135329f1c55e19fd422a9f72dee9caf9d02bac021be" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - nuitka
    - nuitka.build
    - nuitka.codegen
    - nuitka.codegen.templates
    - nuitka.containers
    - nuitka.finalizations
    - nuitka.freezer
    - nuitka.gui
    - nuitka.nodes
    - nuitka.optimizations
    - nuitka.plugins
    - nuitka.profiler
    - nuitka.tree
    - nuitka.utils

  commands:
    - nuitka --help

about:
  home: http://nuitka.net
  license: Apache 2.0
  summary: Python compiler with full language support and CPython compatibility

extra:
  recipe-maintainers:
    - frol
    - kayhayen
