{% set name = "Nuitka" %}
{% set version = "0.5.29" %}
{% set sha256 = "23040bbcddc569946b84037e7d7a4bde20529132b3457440a153a6d56501ca9b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - nuitka
    - nuitka.build
    - nuitka.codegen
    - nuitka.codegen.templates
    - nuitka.containers
    - nuitka.finalizations
    - nuitka.freezer
    - nuitka.gui
    - nuitka.nodes
    - nuitka.optimizations
    - nuitka.plugins
    - nuitka.tools
    - nuitka.tree
    - nuitka.utils

  commands:
    - nuitka --help

about:
  home: http://nuitka.net
  license: Apache 2.0
  summary: Python compiler with full language support and CPython compatibility

extra:
  recipe-maintainers:
    - frol
    - kayhayen
