{% set name = "Nuitka" %}
{% set version = "0.6.0" %}
{% set sha256 = "af0d5575a33e18eee7957bf43c98aed4d1be8a2f609cd9b055288dc1956123c6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - nuitka = nuitka.__main__:main
    - nuitka-run = nuitka.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - nuitka
    - nuitka.build
    - nuitka.codegen
    - nuitka.codegen.templates
    - nuitka.containers
    - nuitka.finalizations
    - nuitka.freezer
    - nuitka.gui
    - nuitka.nodes
    - nuitka.optimizations
    - nuitka.plugins
    - nuitka.tools
    - nuitka.tree
    - nuitka.utils

  commands:
    - nuitka --help

about:
  home: http://nuitka.net
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Python compiler with full language support and CPython compatibility
  description: |
    Nuitka is the Python compiler. It is a seamless replacement or extension
    to the Python interpreter and compiles every construct that CPython 2.6,
    2.7, 3.2, 3.3, 3.4, 3.5, and 3.6 have. It then executes uncompiled code,
    and compiled code together in an extremely compatible manner.

    You can use all Python library modules or and all extension modules freely.
    It translates the Python into a C level program that then uses "libpython"
    to execute in the same way as CPython does. All optimization is aimed at
    avoiding overhead, where it's unnecessary. None is aimed at removing
    compatibility, although slight improvements will occassionally be done,
    where not every bug of standard Python is emulated, e.g. more complete
    error messages are given, but there is a full compatibility mode to
    disable even that.
  doc_url: http://nuitka.net/pages/documentation.html
  dev_url: https://github.com/kayhayen/Nuitka

extra:
  recipe-maintainers:
    - frol
    - kayhayen
