{% set name = "Nuitka" %}
{% set version = "2.7.13" %}
{% set sha256 = "941c6ee2321fea1d297b29669228939200640110be2a8b0bdedfcf6c3bc816b9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - nuitka = nuitka.__main__:main
    - nuitka-run = nuitka.__main__:main
  skip: true  # [python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - libpython-static  # [not win and not py==37]
    - setuptools
    - pip
  run:
    - python
    - libpython-static  # [not win and not py==37]
    - c-compiler
    - patchelf  # [linux]
    - ccache  # [linux]
    - ordered-set  # [py>=37]
    # We don't add any most dependencies here since Nuitka vendors all its dependencies

test:
  imports:
    - nuitka
    - nuitka.build
    - nuitka.containers
    - nuitka.finalizations
    - nuitka.freezer
    - nuitka.importing
    - nuitka.nodes
    - nuitka.optimizations
    - nuitka.plugins
    - nuitka.specs
    - nuitka.tools
    - nuitka.tree
    - nuitka.utils

  commands:
    - nuitka --help
    # Seems to need at least 1.0.6 to work
    # - touch Empty.py
    # - nuitka --show-scons --run Empty.py


about:
  home: https://nuitka.net
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Python compiler with full language support and CPython compatibility
  description: |
    Nuitka is the Python compiler. It is a seamless replacement or extension
    to the Python interpreter and compiles every construct that CPython 2.6,
    2.7, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13 have. It then 
    executes uncompiled code, and compiled code together in an extremely 
    compatible manner.

    You can use all Python library modules or and all extension modules freely.
    It translates the Python into a C level program that then uses "libpython"
    to execute in the same way as CPython does. All optimization is aimed at
    avoiding overhead, where it's unnecessary. None is aimed at removing
    compatibility, although slight improvements will occassionally be done,
    where not every bug of standard Python is emulated, e.g. more complete
    error messages are given, but there is a full compatibility mode to
    disable even that.
  doc_url: https://nuitka.net/user-documentation/
  dev_url: https://github.com/Nuitka/Nuitka

extra:
  recipe-maintainers:
    - kayhayen
