{% set name = "Nuitka" %}
{% set version = "0.5.30" %}
{% set sha256 = "fe5251fa8adbd4114e98c07854c2a9915405fccb6e9c78a51b7d47b700d2ef48" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - nuitka = nuitka.__main__:main
    - nuitka-run = nuitka.__main__:main

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - nuitka
    - nuitka.build
    - nuitka.codegen
    - nuitka.codegen.templates
    - nuitka.containers
    - nuitka.finalizations
    - nuitka.freezer
    - nuitka.gui
    - nuitka.nodes
    - nuitka.optimizations
    - nuitka.plugins
    - nuitka.tools
    - nuitka.tree
    - nuitka.utils

  commands:
    - nuitka --help

about:
  home: http://nuitka.net
  license: Apache 2.0
  summary: Python compiler with full language support and CPython compatibility

extra:
  recipe-maintainers:
    - frol
    - kayhayen
